apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
spec:
  ports:
    - port: {{ .Values.appPort }}
      name: http
  selector:
    app: demo
